name: Deploy mkdocs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Mkdocs and Dependencies
        run: pip install mkdocs mkdocs-material
      - name: Deploy Chain
        run: mkdocs gh-deploy
